# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker CI demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    tags:
      - "v*"
jobs:
  BuildJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u yagizerdem --password-stdin
      - name: Build image
        run: |
          docker build . \
            -t ghcr.io/yagizerdem/${{ github.event.repository.name }}:latest \
            -t ghcr.io/yagizerdem/${{ github.event.repository.name }}:${{ github.ref_name }}

      - name: Push image
        run: |
          docker push ghcr.io/yagizerdem/${{ github.event.repository.name }}:latest
          docker push ghcr.io/yagizerdem/${{ github.event.repository.name }}:${{ github.ref_name }}
