name: "first workflow"

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "build step 1"
        run: echo "hit the build job"

      - name: "build step 2"
        run: echo > build.txt
